services:
  postgres:
    image: postgres:14
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pich
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U postgres -d pich'"]
      interval: 10s
      timeout: 3s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - '3003:3003'
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
